### ISSUE TITLE
Primary lost connection to secondary and no replication but monitor from third site still have connection to both allowing read access to secondary.

### ISSUE THREAD

**Issue by allanharry** [hapostgres/pg_auto_failover#1000] opened 2023-06-26 10:39 UTC
Hi

db-pgxxxxx and db-pgyyyyy in site 1 and 2
Monitor in site 3 is able to connect to both db-pgxxxxx and db-pgyyyyy
db-pgxxxxx cannot connect to db-pgyyyyy and vica versa

My concern is that secondary still available for read all though replication has stopped.

pg_autoctl show state --formation aap_pre_1
         Name |  Node |          Host:Port |         TLI: LSN |   Connection |      Reported State |      Assigned State
--------------+-------+--------------------+------------------+--------------+---------------------+--------------------
db-pgxxxxx |     1 | 10.96.127.111:5432 |  16: 62/**57003458** |    read-only |           secondary |           secondary
db-pgyyyyy |     2 |  10.96.103.35:5432 |  16: 62/**70000000** |   read-write |             primary |             primary

**Should this be allowed from a cluster perspective as secondary is long behind the primary ?**

PG13 running pg_auto_failover 1.6.4 on RHEL 8

Regards Allan

**Comment by xinferum** [comment] 2023-06-30 07:11
Hello.

I will also add our similar ticket for information https://github.com/hapostgres/pg_auto_failover/issues/997

**Comment by dimitri** [comment] 2023-09-25 17:56
Closing, duplicate of #997.

**Closed by dimitri** 2023-09-25 17:56 UTC
